//! Azoth TUI library - Debug trace viewer for obfuscation output.
//!
//! This library provides a terminal-based user interface for viewing
//! obfuscation debug traces generated by the Azoth obfuscator.

pub mod app;
pub mod data;
pub mod event;
pub mod format;
pub mod trace;
pub mod ui;

use std::io;

use crossterm::{
    event::{DisableMouseCapture, EnableMouseCapture},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ratatui::{backend::CrosstermBackend, Terminal};

pub use azoth_core::cfg_ir::TraceEvent;
pub use data::{DebugMetadata, DebugOutput};

use app::App;
use event::run_event_loop;
use ui::ui;

/// Run the TUI application with the given debug output.
///
/// This function sets up the terminal, runs the main event loop,
/// and restores the terminal state on exit.
///
/// # Errors
///
/// Returns an error if terminal setup, event handling, or cleanup fails.
pub fn run(debug: DebugOutput) -> Result<(), Box<dyn std::error::Error>> {
    // Setup terminal
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    // Run app
    let app = App::new(debug);
    let res = run_event_loop(&mut terminal, app, ui);

    // Restore terminal
    disable_raw_mode()?;
    execute!(
        terminal.backend_mut(),
        LeaveAlternateScreen,
        DisableMouseCapture
    )?;
    terminal.show_cursor()?;

    res?;
    Ok(())
}

/// Load debug output from a JSON file.
///
/// # Errors
///
/// Returns an error if the file cannot be read or parsed.
pub fn load_debug_file(path: &std::path::Path) -> Result<DebugOutput, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let debug: DebugOutput = serde_json::from_str(&content)?;
    Ok(debug)
}
