version: '3.8'

services:
  bytecloak-api:
    build:
      context: .
      dockerfile: crates/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - BYTECLOAK_MAX_BYTECODE_SIZE=1048576  # 1MB limit
      - BYTECLOAK_REQUEST_TIMEOUT=30000      # 30 seconds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'