[package]
name = "azoth-utils"
version.workspace = true
edition.workspace = true

[dependencies]
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
thiserror.workspace = true
